version: "3.7"
services:
  drupal:
    image: drupal:8
    ports:
      - 80:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: always
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - "3306:3306"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: